### ISSUE TITLE
Code for Generator

### ISSUE THREAD

**Issue by youwyu** [EmptyJackson/groove#1]
May I ask where is the code for Generator in the paper?
"the level generator is a generative model that is optimized to produce regret-maximizing levels"

**Comment by EmptyJackson** [comment]
The generative model mentioned here is from the definition of Dual Curriculum Design, which describes a class of UED methods consisting of a generator and a curator. We base GROOVE on Prioritized Level Replay, which doesn't optimise a generator and instead curates randomly-sampled levels (see end of Section 3.3).

Hope this helps!
